server:
  port: 8761
spring:
  application:
    name: EUREKA-REGISTRY
# to register a microservice to eureka server
eureka:
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost 