server:
  port: 8087

spring:
 application:
   name: PRODUCT-USER

# add the url of the config server
 config:
      import: configserver:http://localhost:8888

# register with eureka registry
eureka:
  client:
    service-url:
      default-zone: http://EUREKA-REGISTRY













