server:
  port: 8083

spring:
  application:
   name: PRODUCT-INFO


# register with eureka registry
eureka:
  client:
    service-url:
      default-zone: http://EUREKA-REGISTRY

management:
  endpoints:
    web:
      base-path: /management-dashboard
      exposure:
        include: '*'
        exclude: beans
















