server:
  port: 8081

#database specific configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microdb
    username: root	
    password: root

#jpa specific configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update			
  application:
    name: PRODUCT-CATALOG

# register with eureka registry
eureka:
  client:
    service-url:
      default-zone: http://EUREKA-REGISTRY

















